name: monvesto_app
description: "Monvesto Affiliate App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  image_picker: ^1.1.2
  local_auth: ^2.3.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2

  # UI
  google_fonts: ^6.2.1
  provider: ^6.1.2
  url_launcher: ^6.3.0

  # Navigation
  go_router: ^14.2.7

  # Storage
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/